name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install lightweight dependencies
        run: |
          pip install pandas==2.3.3
          pip install numpy==2.3.5
          pip install scikit-learn==1.8.0
          pip install matplotlib==3.10.7
          pip install vaderSentiment==3.3.2
          pip install mlflow==3.12.0
          pip install PyYAML==6.0.3
          pip install langdetect==1.0.9
          pip install pytest==7.4.0

      - name: Run tests with pytest
        run: pytest -v --co -q || echo "No tests found yet"
